// <auto-generated />
namespace Many_To_Many.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sau1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sau1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708021224161_sau1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
